import {
  total,
  shell,
  goil,
  jp,
  allied,
  petrosol,
  puma,
  zen,
  benab,
  starOil,
} from "./images";

const prices = [
  {
    id: 1,
    favorite: false,
    name: "Goil",
    logo: goil,
    Petrol: "13.80",
    Diesel: "13.80",
    Premium: "13.80",
  },
  {
    id: 2,
    favorite: false,
    name: "TotalEnergies",
    logo: total,
    Petrol: "13.80",
    Diesel: "13.80",
    Premium: "15.40",
  },
  {
    id: 3,
    favorite: false,
    name: "Shell",
    logo: shell,
    Petrol: "13.80",
    Diesel: "13.80",
    Premium: "15.30",
  },
  {
    id: 4,
    favorite: false,
    name: "JP",
    logo: jp,
    Petrol: "13.55",
    Diesel: "13.55",
    Premium: "13.75",
  },
  {
    id: 5,
    favorite: false,
    name: "Allied",
    logo: allied,
    Petrol: "13.16",
    Diesel: "13.46",
    Premium: "-",
  },
  {
    id: 6,
    favorite: false,
    name: "StarOil",
    logo: starOil,
    Petrol: "12.99",
    Diesel: "12.99",
    Premium: "-",
  },
  {
    id: 7,
    favorite: false,
    name: "Petrosol",
    logo: petrosol,
    Petrol: "13.44",
    Diesel: "13.57",
    Premium: "-",
  },
  {
    id: 8,
    favorite: false,
    name: "Zen",
    logo: zen,
    Petrol: "12.88",
    Diesel: "12.88",
    Premium: "-",
  },
  {
    id: 9,
    favorite: false,
    name: "Puma",
    logo: puma,
    Petrol: "13.19",
    Diesel: "13.59",
    Premium: "-",
  },
  {
    id: 10,
    favorite: false,
    name: "Benab",
    logo: benab,
    Petrol: "13.06",
    Diesel: "13.38",
    Premium: "-",
  },
];

export default prices;
